<?php

use App\Domains\Administration\Http\Controllers\AdminController;
use App\Domains\Administration\Http\Controllers\HabilitationBoardController;
use App\Domains\Administration\Http\Controllers\RegistreController;
use Illuminate\Support\Facades\Route;

Route::get('/admin/tableau-de-bord', [AdminController::class, 'dashboard']);
Route::get('/admin/utilisateurs', [AdminController::class, 'users']);
Route::get('/admin/structures', [AdminController::class, 'structures']);
Route::post('/admin/utilisateurs', [AdminController::class, 'storeUser']);
Route::get('/admin/utilisateurs/{user}', [AdminController::class, 'showUser']);
Route::put('/admin/utilisateurs/{user}', [AdminController::class, 'updateUser']);
Route::post('/admin/utilisateurs/{user}/desactiver', [AdminController::class, 'deactivate']);
Route::post('/admin/utilisateurs/{user}/roles', [AdminController::class, 'assignRole']);
Route::post('/admin/utilisateurs/{user}/roles/retirer', [AdminController::class, 'removeRole']);
Route::get('/admin/habilitations/catalogue', [AdminController::class, 'catalogue']);
Route::post('/admin/habilitations/verifier', [AdminController::class, 'expliquer']);
Route::put('/admin/utilisateurs/{user}/perimetre', [AdminController::class, 'updateScope']);
Route::get('/admin/roles', [AdminController::class, 'roles']);
Route::put('/admin/roles/{code}', [AdminController::class, 'updateRole']);
Route::delete('/admin/roles/{code}', [AdminController::class, 'destroyRole']);
Route::post('/admin/roles/{code}/permissions', [AdminController::class, 'grantPermission']);
Route::get('/admin/matrice', [AdminController::class, 'matrix']);
Route::get('/admin/roles-permissions', [HabilitationBoardController::class, 'grille']);
Route::put('/admin/roles/{code}/matrice', [HabilitationBoardController::class, 'enregistrer']);
Route::get('/admin/habilitations', [HabilitationBoardController::class, 'liste']);
Route::get('/admin/habilitations/conflit', [HabilitationBoardController::class, 'conflit']);
Route::post('/admin/habilitations', [HabilitationBoardController::class, 'soumettre']);
Route::post('/admin/habilitations/{habilitation}/decision', [HabilitationBoardController::class, 'decider']);
Route::get('/admin/utilisateurs/{user}/droits', [HabilitationBoardController::class, 'droits']);
Route::post('/admin/incompatibilites', [AdminController::class, 'storeIncompatibility']);
Route::post('/admin/incompatibilites/{sodRule}/desactiver', [AdminController::class, 'deactivateIncompatibility']);
Route::get('/admin/delegations', [AdminController::class, 'delegations']);
Route::post('/admin/delegations', [AdminController::class, 'storeDelegation']);
Route::post('/admin/delegations/{delegation}/revoquer', [AdminController::class, 'revokeDelegation']);
Route::get('/admin/interims', [AdminController::class, 'interims']);
Route::post('/admin/interims', [AdminController::class, 'storeInterim']);
Route::post('/admin/interims/{substitution}/cloturer', [AdminController::class, 'closeInterim']);
Route::get('/admin/workflows', [AdminController::class, 'workflows']);
Route::post('/admin/workflows', [AdminController::class, 'storeWorkflow']);
Route::post('/admin/workflows/{definition}/publier', [AdminController::class, 'publishWorkflow']);
Route::post('/admin/workflows/{definition}/versions', [AdminController::class, 'versionWorkflow']);
Route::put('/admin/workflows/versions/{version}', [AdminController::class, 'updateWorkflowVersion']);
Route::get('/admin/seuils', [AdminController::class, 'thresholds']);
Route::post('/admin/seuils', [AdminController::class, 'storeThreshold']);
Route::delete('/admin/nomenclature/{budgetLine}', [AdminController::class, 'destroyNomenclature']);
Route::get('/admin/parametres', [AdminController::class, 'settings']);
Route::put('/admin/regles-metier/{businessRule}', [AdminController::class, 'updateBusinessRule']);
Route::put('/admin/parametres/{key}', [AdminController::class, 'updateSetting']);
Route::patch('/admin/numerotation/{sequence}', [AdminController::class, 'updateSequence']);
Route::get('/admin/integrations', [AdminController::class, 'integrations']);
Route::post('/admin/integrations', [AdminController::class, 'storeIntegration']);
Route::get('/admin/sessions', [AdminController::class, 'sessions']);
Route::post('/admin/sessions', [AdminController::class, 'openSession']);
Route::post('/admin/sessions/{userSession}/revoquer', [AdminController::class, 'revokeSession']);
Route::post('/admin/exercices/{exercice}/rouvrir', [AdminController::class, 'reopenExercice']);
Route::get('/controles/anomalies', [RegistreController::class, 'findings']);
Route::post('/controles/anomalies', [RegistreController::class, 'openFinding']);
Route::post('/controles/anomalies/cloturer', [RegistreController::class, 'closeFinding']);
Route::get('/rapports/execution', [RegistreController::class, 'executionSnapshots']);
Route::get('/imports/preparation', [RegistreController::class, 'importBatches']);
Route::post('/imports/preparation', [RegistreController::class, 'stageImport']);
Route::get('/habilitations/revues', [RegistreController::class, 'review']);
Route::post('/habilitations/revues', [RegistreController::class, 'openReview']);
Route::post('/habilitations/revues/{reference}/confirmer', [RegistreController::class, 'confirmReview']);
