<?php

use App\Domains\Budget\Http\Controllers\BudgetLineController;
use App\Domains\Budget\Http\Controllers\ClotureController;
use App\Domains\Budget\Http\Controllers\EtatsBaseController;
use App\Domains\Budget\Http\Controllers\PreparationController;
use App\Domains\Budget\Http\Controllers\PreparationModuleController;
use App\Domains\Needs\Http\Controllers\ExpressionBesoinController;
use Illuminate\Support\Facades\Route;

Route::get('/lignes-budgetaires', [BudgetLineController::class, 'index']);
Route::post('/lignes-budgetaires/{budgetLine}/mouvements', [BudgetLineController::class, 'move']);
Route::post('/lignes-budgetaires/{budgetLine}/taches', [ExpressionBesoinController::class, 'proposeTask']);
Route::get('/preparation', [PreparationController::class, 'show']);
Route::post('/preparation/ouvrir', [PreparationController::class, 'open']);
Route::patch('/preparation/propositions/{proposal}', [PreparationController::class, 'adjust']);
Route::post('/preparation/propositions/{proposal}/soumettre', [PreparationController::class, 'submit']);
Route::post('/preparation/propositions/{proposal}/retenir', [PreparationController::class, 'retain']);
Route::post('/preparation/{exercice}/adopter', [PreparationController::class, 'adopt'])->whereNumber('exercice');

Route::get('/preparation/referentiel', [PreparationModuleController::class, 'referentiel']);
Route::get('/preparation/campagnes', [PreparationModuleController::class, 'campagnes']);
Route::post('/preparation/campagnes', [PreparationModuleController::class, 'storeCampagne']);
Route::get('/preparation/campagnes/{campaign}', [PreparationModuleController::class, 'showCampagne']);
Route::patch('/preparation/campagnes/{campaign}', [PreparationModuleController::class, 'updateCampagne']);
Route::delete('/preparation/campagnes/{campaign}', [PreparationModuleController::class, 'destroyCampagne']);
Route::post('/preparation/campagnes/{campaign}/ouvrir', [PreparationModuleController::class, 'ouvrir']);
Route::post('/preparation/campagnes/{campaign}/suspendre', [PreparationModuleController::class, 'suspendre']);
Route::post('/preparation/campagnes/{campaign}/prolonger', [PreparationModuleController::class, 'prolonger']);
Route::post('/preparation/campagnes/{campaign}/cloturer', [PreparationModuleController::class, 'cloturer']);
Route::post('/preparation/campagnes/{campaign}/archiver', [PreparationModuleController::class, 'archiver']);
Route::get('/preparation/campagnes/{campaign}/cadrage', [PreparationModuleController::class, 'cadrage']);
Route::post('/preparation/campagnes/{campaign}/etapes', [PreparationModuleController::class, 'storeEtape']);
Route::patch('/preparation/etapes/{step}', [PreparationModuleController::class, 'updateEtape']);
Route::delete('/preparation/etapes/{step}', [PreparationModuleController::class, 'destroyEtape']);
Route::post('/preparation/campagnes/{campaign}/hypotheses', [PreparationModuleController::class, 'storeHypothese']);
Route::patch('/preparation/hypotheses/{hypothesis}', [PreparationModuleController::class, 'updateHypothese']);
Route::post('/preparation/hypotheses/{hypothesis}/publier', [PreparationModuleController::class, 'publierHypothese']);
Route::post('/preparation/hypotheses/{hypothesis}/archiver', [PreparationModuleController::class, 'archiverHypothese']);
Route::post('/preparation/campagnes/{campaign}/orientations', [PreparationModuleController::class, 'storeOrientation']);
Route::patch('/preparation/orientations/{orientation}', [PreparationModuleController::class, 'updateOrientation']);
Route::post('/preparation/orientations/{orientation}/publier', [PreparationModuleController::class, 'publierOrientation']);
Route::post('/preparation/orientations/{orientation}/archiver', [PreparationModuleController::class, 'archiverOrientation']);
Route::post('/preparation/campagnes/{campaign}/enveloppes', [PreparationModuleController::class, 'storeEnveloppe']);
Route::patch('/preparation/enveloppes/{envelope}', [PreparationModuleController::class, 'updateEnveloppe']);
Route::delete('/preparation/enveloppes/{envelope}', [PreparationModuleController::class, 'destroyEnveloppe']);
Route::get('/preparation/dossiers', [PreparationModuleController::class, 'dossiers']);
Route::post('/preparation/dossiers', [PreparationModuleController::class, 'storeDossier']);
Route::get('/preparation/dossiers/{dossier}', [PreparationModuleController::class, 'showDossier']);
Route::patch('/preparation/dossiers/{dossier}', [PreparationModuleController::class, 'updateDossier']);
Route::delete('/preparation/dossiers/{dossier}', [PreparationModuleController::class, 'destroyDossier']);
Route::post('/preparation/dossiers/{dossier}/dupliquer', [PreparationModuleController::class, 'dupliquerDossier']);
Route::post('/preparation/dossiers/{dossier}/soumettre', [PreparationModuleController::class, 'soumettreDossier']);
Route::post('/preparation/dossiers/{dossier}/retourner', [PreparationModuleController::class, 'retournerDossier']);
Route::post('/preparation/dossiers/{dossier}/lignes', [PreparationModuleController::class, 'storeLigne']);
Route::patch('/preparation/lignes/{line}', [PreparationModuleController::class, 'updateLigne']);
Route::delete('/preparation/lignes/{line}', [PreparationModuleController::class, 'destroyLigne']);
Route::post('/preparation/lignes/{line}/details', [PreparationModuleController::class, 'storeDetail']);
Route::patch('/preparation/details/{detail}', [PreparationModuleController::class, 'updateDetail']);
Route::delete('/preparation/details/{detail}', [PreparationModuleController::class, 'destroyDetail']);
Route::post('/preparation/lignes/{line}/periodes', [PreparationModuleController::class, 'storePeriode']);
Route::patch('/preparation/periodes/{period}', [PreparationModuleController::class, 'updatePeriode']);
Route::delete('/preparation/periodes/{period}', [PreparationModuleController::class, 'destroyPeriode']);
Route::post('/preparation/lignes/{line}/financements', [PreparationModuleController::class, 'storeFinancement']);
Route::patch('/preparation/financements/{funding}', [PreparationModuleController::class, 'updateFinancement']);
Route::delete('/preparation/financements/{funding}', [PreparationModuleController::class, 'destroyFinancement']);
Route::post('/preparation/arbitrages', [PreparationModuleController::class, 'storeArbitrage']);
Route::get('/preparation/campagnes/{campaign}/versions', [PreparationModuleController::class, 'versions']);
Route::post('/preparation/campagnes/{campaign}/versions', [PreparationModuleController::class, 'storeVersion']);
Route::get('/preparation/versions/comparer', [PreparationModuleController::class, 'comparer']);
Route::get('/preparation/versions/{version}', [PreparationModuleController::class, 'showVersion']);
Route::post('/preparation/versions/{version}/soumettre', [PreparationModuleController::class, 'soumettreVersion']);
Route::post('/preparation/versions/{version}/retourner', [PreparationModuleController::class, 'retournerVersion']);
Route::post('/preparation/versions/{version}/valider', [PreparationModuleController::class, 'validerVersion']);
Route::post('/preparation/versions/{version}/adopter', [PreparationModuleController::class, 'adopterVersion']);
Route::post('/preparation/versions/{version}/publier', [PreparationModuleController::class, 'publierVersion']);
Route::post('/preparation/versions/{version}/archiver', [PreparationModuleController::class, 'archiverVersion']);
Route::get('/preparation/campagnes/{campaign}/consolidation', [PreparationModuleController::class, 'consolidation']);
Route::get('/preparation/campagnes/{campaign}/export.xlsx', [PreparationModuleController::class, 'excel']);
Route::get('/preparation/campagnes/{campaign}/export.pdf', [PreparationModuleController::class, 'pdf']);
Route::get('/preparation/historique', [PreparationModuleController::class, 'historique']);
Route::post('/preparation/pieces', [PreparationModuleController::class, 'storePiece']);
Route::post('/preparation/pieces/{piece}/remplacer', [PreparationModuleController::class, 'remplacerPiece']);
Route::delete('/preparation/pieces/{piece}', [PreparationModuleController::class, 'destroyPiece']);
Route::get('/preparation/pieces/{piece}/telecharger', [PreparationModuleController::class, 'downloadPiece']);
Route::get('/etats/base', [EtatsBaseController::class, 'show']);
Route::get('/etats/base/export', [EtatsBaseController::class, 'exporter']);
Route::get('/cloture', [ClotureController::class, 'index']);
Route::post('/cloture/{exercice}/periodes', [ClotureController::class, 'assurerPeriodes'])->whereNumber('exercice');
Route::post('/cloture/periodes/{periode}/fermer', [ClotureController::class, 'fermerPeriode'])->whereNumber('periode');
Route::post('/cloture/periodes/{periode}/rouvrir', [ClotureController::class, 'rouvrirPeriode'])->whereNumber('periode');
Route::post('/cloture/{exercice}/demander', [ClotureController::class, 'requestClose']);
Route::post('/cloture/{exercice}/confirmer', [ClotureController::class, 'confirm']);
Route::post('/cloture/{exercice}/archiver', [ClotureController::class, 'archive']);
