/**
 * Référentiel sémantique des icônes : une fonction métier = une icône,
 * partout dans l’application. Importer depuis ici plutôt que directement
 * depuis Font Awesome garantit l’homogénéité.
 */
import {
    faAddressBook,
    faArrowLeft,
    faArrowRight,
    faArrowRightArrowLeft,
    faArrowUpRightDots,
    faBan,
    faBarsStaggered,
    faBell,
    faBolt,
    faBoxArchive,
    faCalendarDays,
    faChartColumn,
    faChartLine,
    faChartPie,
    faCheck,
    faCircleCheck,
    faCircleExclamation,
    faCircleInfo,
    faCircleXmark,
    faClipboardCheck,
    faClockRotateLeft,
    faCoins,
    faComment,
    faCopy,
    faDiagramProject,
    faDownload,
    faEllipsisVertical,
    faEye,
    faFileContract,
    faFileExport,
    faFileInvoiceDollar,
    faFileLines,
    faFilePdf,
    faFilePen,
    faFileShield,
    faFilter,
    faFloppyDisk,
    faGear,
    faArrowDown,
    faArrowUp,
    faClock,
    faHourglassHalf,
    faInbox,
    faMinus,
    faLayerGroup,
    faListCheck,
    faLock,
    faMagnifyingGlass,
    faMoneyBillTransfer,
    faMoneyBillTrendUp,
    faMoneyCheckDollar,
    faPaperclip,
    faPaperPlane,
    faPause,
    faPenToSquare,
    faPlay,
    faPlus,
    faPrint,
    faRotate,
    faRotateLeft,
    faRoute,
    faScaleBalanced,
    faShieldHalved,
    faSignature,
    faSliders,
    faStamp,
    faTrash,
    faTriangleExclamation,
    faUpload,
    faUser,
    faUserCheck,
    faUserShield,
    faUsers,
    faXmark,
} from '@fortawesome/free-solid-svg-icons';

export const ICON = {
    // Actions génériques
    create: faPlus,
    edit: faPenToSquare,
    delete: faTrash,
    view: faEye,
    validate: faCircleCheck,
    approve: faCircleCheck,
    reject: faCircleXmark,
    return: faRotateLeft,
    submit: faPaperPlane,
    transmit: faPaperPlane,
    sign: faSignature,
    visa: faStamp,
    search: faMagnifyingGlass,
    filter: faFilter,
    download: faDownload,
    export: faFileExport,
    print: faPrint,
    pdf: faFilePdf,
    upload: faUpload,
    attachment: faPaperclip,
    save: faFloppyDisk,
    duplicate: faCopy,
    history: faClockRotateLeft,
    calendar: faCalendarDays,
    comment: faComment,
    close: faXmark,
    more: faEllipsisVertical,
    back: faArrowLeft,
    next: faArrowRight,
    open: faArrowRight,
    retry: faRotate,
    suspend: faPause,
    resume: faPlay,
    cancel: faBan,
    lock: faLock,
    check: faCheck,
    takeCharge: faUserCheck,
    execute: faBolt,
    escalate: faArrowUpRightDots,
    archive: faBoxArchive,
    transform: faArrowRightArrowLeft,
    // États
    info: faCircleInfo,
    success: faCircleCheck,
    warning: faTriangleExclamation,
    danger: faCircleExclamation,
    pending: faHourglassHalf,
    // Domaines métier
    tasks: faListCheck,
    inbox: faInbox,
    clock: faClock,
    priorityHigh: faArrowUp,
    priorityLow: faArrowDown,
    priorityNormal: faMinus,
    dashboard: faChartLine,
    need: faFilePen,
    commitment: faFileContract,
    settlement: faFileInvoiceDollar,
    order: faStamp,
    payment: faMoneyBillTransfer,
    paymentBatch: faLayerGroup,
    reconciliation: faScaleBalanced,
    budget: faCoins,
    revenue: faMoneyBillTrendUp,
    suppliers: faAddressBook,
    bankAccount: faMoneyCheckDollar,
    planning: faDiagramProject,
    gantt: faBarsStaggered,
    monitoring: faChartColumn,
    entry: faClipboardCheck,
    gap: faTriangleExclamation,
    actions: faRoute,
    report: faFileLines,
    document: faFileLines,
    synthesis: faChartPie,
    settings: faSliders,
    security: faShieldHalved,
    verifyDocument: faFileShield,
    administration: faGear,
    user: faUser,
    users: faUsers,
    roles: faUserShield,
    notifications: faBell,
} as const;
